server.port=5000

spring.application.name=amazona-backend
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://127.0.0.1:27017/amazona}
spring.data.mongodb.database=amazona

jwt.secret=${JWT_SECRET:somethingsecret_must_be_at_least_256_bits_long_for_hmac_sha256}

# Multipart Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Spring Boot Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
info.app.name=Amazona E-Commerce Java Backend
info.app.description=Spring Boot 3 REST API Service for Amazona E-Commerce
info.app.version=1.0.0
