export default {
  products: [
    // Shirts
    {
      _id: '1',
      name: 'Urban Slim Fit Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80',
      price: 1199,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 127,
      countInStock: 18,
      description: 'A modern slim-fit shirt crafted from premium breathable cotton. Perfect for both casual and semi-formal occasions.',
    },
    {
      _id: '2',
      name: 'Classic Oxford Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=600&q=80',
      price: 1499,
      brand: 'Ralph Lauren',
      rating: 4.3,
      numReviews: 89,
      countInStock: 25,
      description: 'A timeless Oxford shirt with a tailored fit. A wardrobe essential that works from Monday meetings to weekend brunches.',
    },
    {
      _id: '3',
      name: 'Linen Summer Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80',
      price: 1599,
      brand: 'Zara',
      rating: 4.1,
      numReviews: 54,
      countInStock: 12,
      description: 'Light and breathable linen shirt, perfect for hot summer days. Features a relaxed fit and minimal design.',
    },
    {
      _id: '4',
      name: 'Graphic Print Tee',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
      price: 699,
      brand: 'H&M',
      rating: 4.0,
      numReviews: 212,
      countInStock: 50,
      description: 'Express yourself with this bold graphic tee. Made from 100% organic cotton for maximum comfort.',
    },

    // Pants
    {
      _id: '5',
      name: 'Slim Chino Pants',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80',
      price: 1799,
      brand: 'Levi\'s',
      rating: 4.6,
      numReviews: 178,
      countInStock: 20,
      description: 'Versatile slim-fit chinos that bridge the gap between casual and smart casual. Available in multiple colors.',
    },
    {
      _id: '6',
      name: 'Jogger Sweatpants',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600&q=80',
      price: 1599,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 93,
      countInStock: 35,
      description: 'Premium fleece joggers with a modern tapered fit. Perfect for workouts, lounging, or running errands in style.',
    },
    {
      _id: '7',
      name: 'Cargo Utility Pants',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=600&q=80',
      price: 3199,
      brand: 'Carhartt',
      rating: 4.7,
      numReviews: 65,
      countInStock: 15,
      description: 'Durable cargo pants with multiple pockets for maximum utility. Built tough for both work and adventure.',
    },

    // Shoes
    {
      _id: '8',
      name: 'Running Sneakers Pro',
      category: 'Shoes',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
      price: 699,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 342,
      countInStock: 22,
      description: 'High-performance running shoes with advanced cushioning technology and a breathable mesh upper.',
    },
    {
      _id: '9',
      name: 'Classic White Leather Shoes',
      category: 'Shoes',
      image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80',
      price: 1999,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 188,
      countInStock: 30,
      description: 'Iconic clean white sneakers with premium leather upper. A timeless silhouette that goes with everything.',
    },
    {
      _id: '10',
      name: 'Hiking Boots',
      category: 'Shoes',
      image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&q=80',
      price: 1999,
      brand: 'Timberland',
      rating: 4.6,
      numReviews: 77,
      countInStock: 10,
      description: 'Waterproof hiking boots with ankle support and a grippy sole. Ready for any terrain.',
    },

    // Accessories
    {
      _id: '11',
      name: 'Polarized Sunglasses',
      category: 'Accessories',
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80',
      price: 499,
      brand: 'Ray-Ban',
      rating: 4.6,
      numReviews: 88,
      countInStock: 25,
      description: 'Classic style sunglasses with 100% UV protection and high quality polarized lenses.',
    },
    {
      _id: '12',
      name: 'Minimalist Watch',
      category: 'Accessories',
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
      price: 1999,
      brand: 'Peter England',
      rating: 4.7,
      numReviews: 523,
      countInStock: 8,
      description: 'A sleek, minimalist watch with a rose gold case and a genuine leather strap. Timeless elegance on your wrist.',
    },
  ],
};