server.port=5000

spring.data.mongodb.uri=mongodb://127.0.0.1:27017/amazona
spring.data.mongodb.database=amazona

jwt.secret=somethingsecret_must_be_at_least_256_bits_long_for_hmac_sha256
paypal.client.id=sb

# Multipart Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
